export const FETCH_TRACKINGS = 'FETCH_TRACKINGS';
export const CREATE_TRACKING_PROPERTY_CHANGED = 'CREATE_TRACKING_PROP_CHANGED';
export const TRACKING_CREATED = 'TRACKING_CREATED';
export const DELETE_TRACKING = 'DELETE_TRACKING';
export const EDIT_TRACKING = 'EDIT_TRACKING';

